export const GTO_CHAPTERS = [
  { id: 1, title: "位置與強度：從 UTG 到 BTN 的策略框架", tags: ["preflop","position","range"] },
  { id: 2, title: "RFI 開局範圍：不同位置的開局策略", tags: ["preflop","rfi"] },
  { id: 3, title: "3-Bet 與 4-Bet：範圍構建與平衡", tags: ["preflop","3bet","4bet"] },
  { id: 4, title: "Call vs 3-Bet：在什麼位置該 Call？", tags: ["preflop","call","defense"] },
  { id: 5, title: "對抗 3-Bet：5-Bet、Call、Fold 的決策架構", tags: ["preflop","3bet","4bet","5bet"] },
  { id: 6, title: "盲位防守：SB/BB 的完整防守策略", tags: ["preflop","blind","defense"] },
  { id: 7, title: "SPR 基礎：預先規劃後續三街", tags: ["preflop","spr"] },
  { id: 8, title: "Stack Depth：不同籌碼深度的打法", tags: ["preflop","stack","depth"] },
  { id: 9, title: "短碼 vs 深碼：調整你的開局策略", tags: ["preflop","stack"] },
  { id: 10, title: "常見 Preflop Leak：過度 Call、過度 3-Bet、弱範圍開局", tags: ["preflop","leak"] },

  { id: 11, title: "牌面結構：乾牌面 / 濕牌面 / 配對牌面", tags: ["flop","texture"] },
  { id: 12, title: "Range Advantage：誰在 Flop 佔優勢？", tags: ["flop","range"] },
  { id: 13, title: "C-Bet 原則：何時小注、何時大注？", tags: ["flop","cbet","sizing"] },
  { id: 14, title: "Flop 小注策略：1/4–1/3 的高頻使用", tags: ["flop","cbet","sizing"] },
  { id: 15, title: "大尺寸（2/3–3/4）與 Polar Range", tags: ["flop","sizing","polar"] },
  { id: 16, title: "Check-Call、Check-Raise 的使用時機", tags: ["flop","xcall","xraise"] },
  { id: 17, title: "對抗 C-Bet：Call? Raise? Fold?", tags: ["flop","defense"] },
  { id: 18, title: "Position Effect：前位 vs 後位的策略差異", tags: ["flop","position"] },
  { id: 19, title: "Flop 常見 Leak：錯用小注、過度 Check、過度 Raise", tags: ["flop","leak"] },

  { id: 20, title: "Turn 牌面變化：Kicker、連線、同花完成", tags: ["turn","texture"] },
  { id: 21, title: "Turn Second Barrel：何時該繼續？何時該放棄？", tags: ["turn","barrel"] },
  { id: 22, title: "Turn 大尺寸與 Polarization", tags: ["turn","sizing","polar"] },
  { id: 23, title: "Turn Check-Call：如何避免過度被動？", tags: ["turn","xcall"] },
  { id: 24, title: "Turn Check-Raise：何時代表強度？", tags: ["turn","xraise"] },
  { id: 25, title: "Turn Probe-Bet（HB）的策略使用", tags: ["turn","probe"] },
  { id: 26, title: "Turn Overbet：高級武器與使用邏輯", tags: ["turn","overbet"] },
  { id: 27, title: "對抗 Turn 加注：你該怎麼保護自己的範圍？", tags: ["turn","defense"] },
  { id: 28, title: "小籌碼時 Turn 該更激進嗎？", tags: ["turn","stack"] },
  { id: 29, title: "Turn 常見 Leak：無計畫的 barrel / 無意義的 call", tags: ["turn","leak"] },
  { id: 30, title: "用 Turn 決定 River 計畫：Polar vs Merge", tags: ["turn","plan"] },

  { id: 31, title: "River 牌力 vs 範圍：先看自己在哪個邊界", tags: ["river","range"] },
  { id: 32, title: "Thin Value：如何抓住最後的價值？", tags: ["river","value"] },
  { id: 33, title: "Bluff Catch：如何判斷對手 Bluff 足不足？", tags: ["river","bluffcatch"] },
  { id: 34, title: "Overbet River：極化價值與 Bluff 的平衡", tags: ["river","overbet","polar"] },
  { id: 35, title: "Blocker 理論（阻擋牌）", tags: ["river","blocker"] },
  { id: 36, title: "S-Ratio：用底池比例判斷是否能下注", tags: ["river","sizing","spr"] },
  { id: 37, title: "對抗 River All-in：如何做零點決策？", tags: ["river","jam","defense"] },
  { id: 38, title: "River Check-Call 與 Check-Fold 的正確比例", tags: ["river","xcall","xfold"] },
  { id: 39, title: "River Check-Raise：高階武器與風險", tags: ["river","xraise"] },
  { id: 40, title: "River 常見 Leak：過度 hero call / 過度被動", tags: ["river","leak"] },

  { id: 41, title: "Polar vs Merge：如何建立真正的 GTO 範圍？", tags: ["advanced","range","polar"] },
  { id: 42, title: "Range Construction：用組合數構建完整範圍", tags: ["advanced","range"] },
  { id: 43, title: "GTO Solver 基礎（Pio、GTO+）", tags: ["advanced","solver"] },
  { id: 44, title: "Exploit（剝削）：如何利用對手的習慣？", tags: ["advanced","exploit"] },
  { id: 45, title: "Player Pool Tendency：一般玩家的偏誤", tags: ["advanced","population"] },
  { id: 46, title: "多桌與多玩家玩法（MTT / Cash 通用）", tags: ["advanced","mtt"] },
  { id: 47, title: "心態管理（Mental Game）", tags: ["advanced","mental"] },
  { id: 48, title: "常見職業牌手思維模式（高階）", tags: ["advanced","pro"] },
  { id: 49, title: "完整三街計畫：從 Preflop 到 River 的連貫性", tags: ["advanced","plan"] },
  { id: 50, title: "整體策略整合：打造屬於自己的 GTO+ 機器思維", tags: ["advanced","integration"] },
];
